### ISSUE TITLE
Error: this.onSetup is not a function

### ISSUE THREAD

**Issue by nunof07** [leandroz/ionic-modal-component#1]
Hi,

Thank you for this component. I've been using it successfully on Android and web, but when running in iOS with Cordova I get the error message:

```
Error: this.onSetup is not a function. (In 'this.onSetup({$removeModal:this.removeModal.bind(this)})', 'this.onSetup' is undefined)
```

`on-setup` is actually defined. Not sure why it complains about that. Seems a bit strange that this only happens in iOS.

I can try putting a check in the onSetup call in your modal component, but then my onSetup function won't be called.

Have you encountered this issue before?

**Comment by leandroz** [comment]
Hi @nunof07 !

Thanks for reporting this, busy days ending the year but will take a look as soon as posible.

Can you show me how are you using it? both template and the onSetup function that you have passed to the component so I have an idea.

**Comment by nunof07** [comment]
Hi @leandroz, thank you for your help.

I will try to setup a demo as soon as possible, but just to give you some more info in the meantime, I think the issue might actually not have anything to do with iOS/Android but rather with the latest version of angular (?).

I first saw the issue in iOS so I assumed it had something to do with it, but I forgot that since I was building in a different machine npm installed the latest minor releases of all packages in my project.

Now I'm thinking that might have something to do with it, because when I tried setting up the project recently in a different machine, even in the web browser on Windows, I saw the same issue, which I had not seen previously.

In any case I will try to reproduce this issue separately to see where the fault actually lies or if it's some problem in the way I'm using it.

**Comment by nunof07** [comment]
I was able to reproduce this issue separately using the example from the readme.

Here is the CodePen: [http://codepen.io/anon/pen/bBzQrY](http://codepen.io/anon/pen/bBzQrY)

I don't think the issue has anything to do with this component though, so maybe you can close it.

I think it has to do with the version of Angular and Ionic I have included. If instead of including Angular and Ionic separately you use the ionic.bundle.js, the issue doesn't occur, because the ionic.bundle.js uses and older version of Angular and some other Angular modules.

Or am I missing something?

**Comment by leandroz** [comment]
@nunof07 thanks for the codepen, I saw the problem and I believe that depending on the Angular version the binding of the events are not set during the constructor.

If I add a $timeout when firing the setup event everything works well, see here: http://codepen.io/leandroz/pen/egVKNP

**Comment by nunof07** [comment]
Thank you for fixing this. Appreciated.
