### ISSUE TITLE
back button is not working on Android

### ISSUE THREAD

**Issue by AdrienDC** [leandroz/ionic-modal-component#2]
Hi,
tried this modal component which is exactly what I was looking for but unfortunately, the back button is not closing the modal.

Any advises?

Thanks

**Comment by leandroz** [comment]
Hi @AdrienDC , you can do something like this in the controller responsable for handling the state of the modal:

`
$ionicPlatform.onHardwareBackButton(function() {
  modalIsOpen = false;
})
`

**Comment by AdrienDC** [comment]
Thanks @leandroz , this is what I end up with as a workaround
